/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SoulCastGovernor__factory } from "./SoulCastGovernor__factory";
export { SoulCastToken__factory } from "./SoulCastToken__factory";
