/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SoulCastGovernor } from "./SoulCastGovernor";
export type { SoulCastToken } from "./SoulCastToken";
