/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PredictionMarket {
  export type MarketStruct = {
    id: BigNumberish;
    creator: AddressLike;
    question: string;
    category: string;
    endDate: BigNumberish;
    yesPool: BigNumberish;
    noPool: BigNumberish;
    totalVolume: BigNumberish;
    status: BigNumberish;
    outcome: BigNumberish;
    isResolved: boolean;
    resolutionTime: BigNumberish;
  };

  export type MarketStructOutput = [
    id: bigint,
    creator: string,
    question: string,
    category: string,
    endDate: bigint,
    yesPool: bigint,
    noPool: bigint,
    totalVolume: bigint,
    status: bigint,
    outcome: bigint,
    isResolved: boolean,
    resolutionTime: bigint
  ] & {
    id: bigint;
    creator: string;
    question: string;
    category: string;
    endDate: bigint;
    yesPool: bigint;
    noPool: bigint;
    totalVolume: bigint;
    status: bigint;
    outcome: bigint;
    isResolved: boolean;
    resolutionTime: bigint;
  };

  export type BetStruct = {
    bettor: AddressLike;
    amount: BigNumberish;
    side: boolean;
    priceAtBet: BigNumberish;
    timestamp: BigNumberish;
    claimed: boolean;
  };

  export type BetStructOutput = [
    bettor: string,
    amount: bigint,
    side: boolean,
    priceAtBet: bigint,
    timestamp: bigint,
    claimed: boolean
  ] & {
    bettor: string;
    amount: bigint;
    side: boolean;
    priceAtBet: bigint;
    timestamp: bigint;
    claimed: boolean;
  };
}

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_BET_AMOUNT"
      | "MIN_BET_AMOUNT"
      | "PLATFORM_FEE_BPS"
      | "calculatePayout"
      | "cancelMarket"
      | "claimWinnings"
      | "closeMarket"
      | "createMarket"
      | "getClaimableAmount"
      | "getMarket"
      | "getMarketCount"
      | "getMarketPrices"
      | "getUserBets"
      | "marketBetCount"
      | "marketCounter"
      | "markets"
      | "owner"
      | "paymentToken"
      | "placeBet"
      | "platformFeeRecipient"
      | "renounceOwnership"
      | "resolveMarket"
      | "transferOwnership"
      | "useNativeToken"
      | "userBets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetClaimed"
      | "BetPlaced"
      | "MarketClosed"
      | "MarketCreated"
      | "MarketResolved"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_BET_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_BET_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePayout",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableAmount",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketPrices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBets",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketBetCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "useNativeToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userBets",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_BET_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_BET_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketBetCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "useNativeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userBets", data: BytesLike): Result;
}

export namespace BetClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    bettor: AddressLike,
    amount: BigNumberish,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    bettor: string,
    amount: bigint,
    payout: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    bettor: string;
    amount: bigint;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    bettor: AddressLike,
    side: boolean,
    amount: BigNumberish,
    priceAtBet: BigNumberish,
    yesPool: BigNumberish,
    noPool: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    bettor: string,
    side: boolean,
    amount: bigint,
    priceAtBet: bigint,
    yesPool: bigint,
    noPool: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    bettor: string;
    side: boolean;
    amount: bigint;
    priceAtBet: bigint;
    yesPool: bigint;
    noPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketClosedEvent {
  export type InputTuple = [marketId: BigNumberish];
  export type OutputTuple = [marketId: bigint];
  export interface OutputObject {
    marketId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    creator: AddressLike,
    question: string,
    category: string,
    endDate: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    creator: string,
    question: string,
    category: string,
    endDate: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    creator: string;
    question: string;
    category: string;
    endDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    outcome: BigNumberish,
    resolutionTime: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    outcome: bigint,
    resolutionTime: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    outcome: bigint;
    resolutionTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BET_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  MIN_BET_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  calculatePayout: TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean, _amount: BigNumberish],
    [bigint],
    "view"
  >;

  cancelMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimWinnings: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  closeMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMarket: TypedContractMethod<
    [
      _question: string,
      _category: string,
      _endDate: BigNumberish,
      _initialLiquidity: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  getClaimableAmount: TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [bigint],
    "view"
  >;

  getMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [PredictionMarket.MarketStructOutput],
    "view"
  >;

  getMarketCount: TypedContractMethod<[], [bigint], "view">;

  getMarketPrices: TypedContractMethod<
    [_marketId: BigNumberish],
    [[bigint, bigint] & { yesPriceBps: bigint; noPriceBps: bigint }],
    "view"
  >;

  getUserBets: TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [PredictionMarket.BetStructOutput[]],
    "view"
  >;

  marketBetCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  marketCounter: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        creator: string;
        question: string;
        category: string;
        endDate: bigint;
        yesPool: bigint;
        noPool: bigint;
        totalVolume: bigint;
        status: bigint;
        outcome: bigint;
        isResolved: boolean;
        resolutionTime: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  placeBet: TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean, _amount: BigNumberish],
    [void],
    "payable"
  >;

  platformFeeRecipient: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveMarket: TypedContractMethod<
    [_marketId: BigNumberish, _outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  useNativeToken: TypedContractMethod<[], [boolean], "view">;

  userBets: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [
      [string, bigint, boolean, bigint, bigint, boolean] & {
        bettor: string;
        amount: bigint;
        side: boolean;
        priceAtBet: bigint;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BET_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BET_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculatePayout"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean, _amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closeMarket"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      _question: string,
      _category: string,
      _endDate: BigNumberish,
      _initialLiquidity: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getClaimableAmount"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [_marketId: BigNumberish],
    [PredictionMarket.MarketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarketPrices"
  ): TypedContractMethod<
    [_marketId: BigNumberish],
    [[bigint, bigint] & { yesPriceBps: bigint; noPriceBps: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBets"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [PredictionMarket.BetStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketBetCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        creator: string;
        question: string;
        category: string;
        endDate: bigint;
        yesPool: bigint;
        noPool: bigint;
        totalVolume: bigint;
        status: bigint;
        outcome: bigint;
        isResolved: boolean;
        resolutionTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _side: boolean, _amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "platformFeeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _outcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "useNativeToken"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "userBets"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [
      [string, bigint, boolean, bigint, bigint, boolean] & {
        bettor: string;
        amount: bigint;
        side: boolean;
        priceAtBet: bigint;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BetClaimed"
  ): TypedContractEvent<
    BetClaimedEvent.InputTuple,
    BetClaimedEvent.OutputTuple,
    BetClaimedEvent.OutputObject
  >;
  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "MarketClosed"
  ): TypedContractEvent<
    MarketClosedEvent.InputTuple,
    MarketClosedEvent.OutputTuple,
    MarketClosedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BetClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      BetClaimedEvent.InputTuple,
      BetClaimedEvent.OutputTuple,
      BetClaimedEvent.OutputObject
    >;
    BetClaimed: TypedContractEvent<
      BetClaimedEvent.InputTuple,
      BetClaimedEvent.OutputTuple,
      BetClaimedEvent.OutputObject
    >;

    "BetPlaced(uint256,address,bool,uint256,uint256,uint256,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "MarketClosed(uint256)": TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;
    MarketClosed: TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;

    "MarketCreated(uint256,address,string,string,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(uint256,uint8,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
