/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SoulLiquidityManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateRewards"
      | "claimRewards"
      | "fundRewardsPool"
      | "getStakerInfo"
      | "isPoolLocked"
      | "liquidityPools"
      | "lockLiquidity"
      | "lpStakes"
      | "lpToken"
      | "minLockDuration"
      | "owner"
      | "poolCount"
      | "recordLiquidityPool"
      | "renounceOwnership"
      | "setLPToken"
      | "setMinLockDuration"
      | "setStakingRewardRate"
      | "soulToken"
      | "stakeLP"
      | "stakingRewardRateBps"
      | "stakingRewardsPool"
      | "totalLPStaked"
      | "transferOwnership"
      | "unlockLiquidity"
      | "unstakeLP"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LPStaked"
      | "LPUnstaked"
      | "LiquidityLocked"
      | "LiquidityPoolCreated"
      | "LiquidityUnlocked"
      | "OwnershipTransferred"
      | "RewardsClaimed"
      | "RewardsPoolFunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundRewardsPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakerInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPoolLocked",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityPools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lpStakes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "lpToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minLockDuration",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "poolCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordLiquidityPool",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLPToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinLockDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingRewardRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "soulToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "stakeLP",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingRewardRateBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakingRewardsPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalLPStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeLP",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundRewardsPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakerInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPoolLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpStakes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minLockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordLiquidityPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setLPToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinLockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingRewardRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "soulToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeLP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakingRewardRateBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingRewardsPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLPStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstakeLP", data: BytesLike): Result;
}

export namespace LPStakedEvent {
  export type InputTuple = [staker: AddressLike, amount: BigNumberish];
  export type OutputTuple = [staker: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPUnstakedEvent {
  export type InputTuple = [staker: AddressLike, amount: BigNumberish];
  export type OutputTuple = [staker: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityLockedEvent {
  export type InputTuple = [poolId: BigNumberish, lockUntil: BigNumberish];
  export type OutputTuple = [poolId: bigint, lockUntil: bigint];
  export interface OutputObject {
    poolId: bigint;
    lockUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityPoolCreatedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    poolAddress: AddressLike,
    token0: AddressLike,
    token1: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    lpTokens: BigNumberish,
    dexName: string
  ];
  export type OutputTuple = [
    poolId: bigint,
    poolAddress: string,
    token0: string,
    token1: string,
    amount0: bigint,
    amount1: bigint,
    lpTokens: bigint,
    dexName: string
  ];
  export interface OutputObject {
    poolId: bigint;
    poolAddress: string;
    token0: string;
    token1: string;
    amount0: bigint;
    amount1: bigint;
    lpTokens: bigint;
    dexName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityUnlockedEvent {
  export type InputTuple = [poolId: BigNumberish];
  export type OutputTuple = [poolId: bigint];
  export interface OutputObject {
    poolId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [staker: AddressLike, amount: BigNumberish];
  export type OutputTuple = [staker: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsPoolFundedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SoulLiquidityManager extends BaseContract {
  connect(runner?: ContractRunner | null): SoulLiquidityManager;
  waitForDeployment(): Promise<this>;

  interface: SoulLiquidityManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateRewards: TypedContractMethod<
    [_staker: AddressLike],
    [bigint],
    "view"
  >;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  fundRewardsPool: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getStakerInfo: TypedContractMethod<
    [_staker: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        stakedAmount: bigint;
        pendingRewards: bigint;
        totalEarned: bigint;
        stakedAt: bigint;
      }
    ],
    "view"
  >;

  isPoolLocked: TypedContractMethod<[_poolId: BigNumberish], [boolean], "view">;

  liquidityPools: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        poolAddress: string;
        token0: string;
        token1: string;
        token0Amount: bigint;
        token1Amount: bigint;
        lpTokens: bigint;
        lockUntil: bigint;
        locked: boolean;
        dexName: string;
      }
    ],
    "view"
  >;

  lockLiquidity: TypedContractMethod<
    [_poolId: BigNumberish, _lockDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  lpStakes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint] & {
        staker: string;
        lpTokenAmount: bigint;
        stakedAt: bigint;
        rewardsEarned: bigint;
        lastRewardClaim: bigint;
      }
    ],
    "view"
  >;

  lpToken: TypedContractMethod<[], [string], "view">;

  minLockDuration: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  poolCount: TypedContractMethod<[], [bigint], "view">;

  recordLiquidityPool: TypedContractMethod<
    [
      _poolAddress: AddressLike,
      _token0: AddressLike,
      _token1: AddressLike,
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _lpTokens: BigNumberish,
      _dexName: string
    ],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setLPToken: TypedContractMethod<
    [_lpToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setMinLockDuration: TypedContractMethod<
    [_duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setStakingRewardRate: TypedContractMethod<
    [_rateBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  soulToken: TypedContractMethod<[], [string], "view">;

  stakeLP: TypedContractMethod<
    [_lpTokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakingRewardRateBps: TypedContractMethod<[], [bigint], "view">;

  stakingRewardsPool: TypedContractMethod<[], [bigint], "view">;

  totalLPStaked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockLiquidity: TypedContractMethod<
    [_poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unstakeLP: TypedContractMethod<
    [_lpTokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateRewards"
  ): TypedContractMethod<[_staker: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundRewardsPool"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getStakerInfo"
  ): TypedContractMethod<
    [_staker: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        stakedAmount: bigint;
        pendingRewards: bigint;
        totalEarned: bigint;
        stakedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPoolLocked"
  ): TypedContractMethod<[_poolId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "liquidityPools"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        poolAddress: string;
        token0: string;
        token1: string;
        token0Amount: bigint;
        token1Amount: bigint;
        lpTokens: bigint;
        lockUntil: bigint;
        locked: boolean;
        dexName: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockLiquidity"
  ): TypedContractMethod<
    [_poolId: BigNumberish, _lockDuration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lpStakes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint] & {
        staker: string;
        lpTokenAmount: bigint;
        stakedAt: bigint;
        rewardsEarned: bigint;
        lastRewardClaim: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lpToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "minLockDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordLiquidityPool"
  ): TypedContractMethod<
    [
      _poolAddress: AddressLike,
      _token0: AddressLike,
      _token1: AddressLike,
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _lpTokens: BigNumberish,
      _dexName: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLPToken"
  ): TypedContractMethod<[_lpToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinLockDuration"
  ): TypedContractMethod<[_duration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakingRewardRate"
  ): TypedContractMethod<[_rateBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "soulToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stakeLP"
  ): TypedContractMethod<[_lpTokenAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingRewardRateBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakingRewardsPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalLPStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockLiquidity"
  ): TypedContractMethod<[_poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeLP"
  ): TypedContractMethod<[_lpTokenAmount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "LPStaked"
  ): TypedContractEvent<
    LPStakedEvent.InputTuple,
    LPStakedEvent.OutputTuple,
    LPStakedEvent.OutputObject
  >;
  getEvent(
    key: "LPUnstaked"
  ): TypedContractEvent<
    LPUnstakedEvent.InputTuple,
    LPUnstakedEvent.OutputTuple,
    LPUnstakedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityLocked"
  ): TypedContractEvent<
    LiquidityLockedEvent.InputTuple,
    LiquidityLockedEvent.OutputTuple,
    LiquidityLockedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityPoolCreated"
  ): TypedContractEvent<
    LiquidityPoolCreatedEvent.InputTuple,
    LiquidityPoolCreatedEvent.OutputTuple,
    LiquidityPoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityUnlocked"
  ): TypedContractEvent<
    LiquidityUnlockedEvent.InputTuple,
    LiquidityUnlockedEvent.OutputTuple,
    LiquidityUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsPoolFunded"
  ): TypedContractEvent<
    RewardsPoolFundedEvent.InputTuple,
    RewardsPoolFundedEvent.OutputTuple,
    RewardsPoolFundedEvent.OutputObject
  >;

  filters: {
    "LPStaked(address,uint256)": TypedContractEvent<
      LPStakedEvent.InputTuple,
      LPStakedEvent.OutputTuple,
      LPStakedEvent.OutputObject
    >;
    LPStaked: TypedContractEvent<
      LPStakedEvent.InputTuple,
      LPStakedEvent.OutputTuple,
      LPStakedEvent.OutputObject
    >;

    "LPUnstaked(address,uint256)": TypedContractEvent<
      LPUnstakedEvent.InputTuple,
      LPUnstakedEvent.OutputTuple,
      LPUnstakedEvent.OutputObject
    >;
    LPUnstaked: TypedContractEvent<
      LPUnstakedEvent.InputTuple,
      LPUnstakedEvent.OutputTuple,
      LPUnstakedEvent.OutputObject
    >;

    "LiquidityLocked(uint256,uint256)": TypedContractEvent<
      LiquidityLockedEvent.InputTuple,
      LiquidityLockedEvent.OutputTuple,
      LiquidityLockedEvent.OutputObject
    >;
    LiquidityLocked: TypedContractEvent<
      LiquidityLockedEvent.InputTuple,
      LiquidityLockedEvent.OutputTuple,
      LiquidityLockedEvent.OutputObject
    >;

    "LiquidityPoolCreated(uint256,address,address,address,uint256,uint256,uint256,string)": TypedContractEvent<
      LiquidityPoolCreatedEvent.InputTuple,
      LiquidityPoolCreatedEvent.OutputTuple,
      LiquidityPoolCreatedEvent.OutputObject
    >;
    LiquidityPoolCreated: TypedContractEvent<
      LiquidityPoolCreatedEvent.InputTuple,
      LiquidityPoolCreatedEvent.OutputTuple,
      LiquidityPoolCreatedEvent.OutputObject
    >;

    "LiquidityUnlocked(uint256)": TypedContractEvent<
      LiquidityUnlockedEvent.InputTuple,
      LiquidityUnlockedEvent.OutputTuple,
      LiquidityUnlockedEvent.OutputObject
    >;
    LiquidityUnlocked: TypedContractEvent<
      LiquidityUnlockedEvent.InputTuple,
      LiquidityUnlockedEvent.OutputTuple,
      LiquidityUnlockedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "RewardsPoolFunded(uint256)": TypedContractEvent<
      RewardsPoolFundedEvent.InputTuple,
      RewardsPoolFundedEvent.OutputTuple,
      RewardsPoolFundedEvent.OutputObject
    >;
    RewardsPoolFunded: TypedContractEvent<
      RewardsPoolFundedEvent.InputTuple,
      RewardsPoolFundedEvent.OutputTuple,
      RewardsPoolFundedEvent.OutputObject
    >;
  };
}
