/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SoulVesting {
  export type VestingScheduleStruct = {
    beneficiary: AddressLike;
    totalAmount: BigNumberish;
    released: BigNumberish;
    startTime: BigNumberish;
    duration: BigNumberish;
    cliffDuration: BigNumberish;
    revocable: boolean;
    revoked: boolean;
    earlyUnlockPenalty: BigNumberish;
  };

  export type VestingScheduleStructOutput = [
    beneficiary: string,
    totalAmount: bigint,
    released: bigint,
    startTime: bigint,
    duration: bigint,
    cliffDuration: bigint,
    revocable: boolean,
    revoked: boolean,
    earlyUnlockPenalty: bigint
  ] & {
    beneficiary: string;
    totalAmount: bigint;
    released: bigint;
    startTime: bigint;
    duration: bigint;
    cliffDuration: bigint;
    revocable: boolean;
    revoked: boolean;
    earlyUnlockPenalty: bigint;
  };
}

export interface SoulVestingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchCreateVestingSchedules"
      | "beneficiarySchedules"
      | "createVestingSchedule"
      | "earlyUnlock"
      | "getBeneficiaryInfo"
      | "getBeneficiarySchedules"
      | "getReleasableAmount"
      | "getSchedule"
      | "getVestedAmount"
      | "owner"
      | "release"
      | "renounceOwnership"
      | "revoke"
      | "soulToken"
      | "totalReleased"
      | "totalVestingAmount"
      | "transferOwnership"
      | "vestingScheduleCount"
      | "vestingSchedules"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EarlyUnlock"
      | "OwnershipTransferred"
      | "TokensReleased"
      | "VestingRevoked"
      | "VestingScheduleCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchCreateVestingSchedules",
    values: [
      AddressLike[],
      BigNumberish[],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiarySchedules",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createVestingSchedule",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "earlyUnlock",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaryInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiarySchedules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReleasableAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSchedule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestedAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "soulToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVestingAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingScheduleCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vestingSchedules",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchCreateVestingSchedules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beneficiarySchedules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "earlyUnlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiarySchedules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReleasableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "soulToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVestingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingScheduleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingSchedules",
    data: BytesLike
  ): Result;
}

export namespace EarlyUnlockEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    beneficiary: AddressLike,
    amount: BigNumberish,
    penalty: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    beneficiary: string,
    amount: bigint,
    penalty: bigint
  ];
  export interface OutputObject {
    scheduleId: bigint;
    beneficiary: string;
    amount: bigint;
    penalty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensReleasedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    beneficiary: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    beneficiary: string,
    amount: bigint
  ];
  export interface OutputObject {
    scheduleId: bigint;
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingRevokedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    beneficiary: AddressLike,
    revokedAmount: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    beneficiary: string,
    revokedAmount: bigint
  ];
  export interface OutputObject {
    scheduleId: bigint;
    beneficiary: string;
    revokedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingScheduleCreatedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    beneficiary: AddressLike,
    totalAmount: BigNumberish,
    startTime: BigNumberish,
    duration: BigNumberish,
    cliffDuration: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    beneficiary: string,
    totalAmount: bigint,
    startTime: bigint,
    duration: bigint,
    cliffDuration: bigint
  ];
  export interface OutputObject {
    scheduleId: bigint;
    beneficiary: string;
    totalAmount: bigint;
    startTime: bigint;
    duration: bigint;
    cliffDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SoulVesting extends BaseContract {
  connect(runner?: ContractRunner | null): SoulVesting;
  waitForDeployment(): Promise<this>;

  interface: SoulVestingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchCreateVestingSchedules: TypedContractMethod<
    [
      _beneficiaries: AddressLike[],
      _totalAmounts: BigNumberish[],
      _startTime: BigNumberish,
      _duration: BigNumberish,
      _cliffDuration: BigNumberish,
      _revocable: boolean,
      _earlyUnlockPenalty: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  beneficiarySchedules: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  createVestingSchedule: TypedContractMethod<
    [
      _beneficiary: AddressLike,
      _totalAmount: BigNumberish,
      _startTime: BigNumberish,
      _duration: BigNumberish,
      _cliffDuration: BigNumberish,
      _revocable: boolean,
      _earlyUnlockPenalty: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  earlyUnlock: TypedContractMethod<
    [_scheduleId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBeneficiaryInfo: TypedContractMethod<
    [_beneficiary: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalVested: bigint;
        totalReleasable: bigint;
        beneficiaryTotalReleased: bigint;
      }
    ],
    "view"
  >;

  getBeneficiarySchedules: TypedContractMethod<
    [_beneficiary: AddressLike],
    [bigint[]],
    "view"
  >;

  getReleasableAmount: TypedContractMethod<
    [_scheduleId: BigNumberish],
    [bigint],
    "view"
  >;

  getSchedule: TypedContractMethod<
    [_scheduleId: BigNumberish],
    [SoulVesting.VestingScheduleStructOutput],
    "view"
  >;

  getVestedAmount: TypedContractMethod<
    [_scheduleId: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  release: TypedContractMethod<
    [_scheduleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revoke: TypedContractMethod<
    [_scheduleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  soulToken: TypedContractMethod<[], [string], "view">;

  totalReleased: TypedContractMethod<[], [bigint], "view">;

  totalVestingAmount: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vestingScheduleCount: TypedContractMethod<[], [bigint], "view">;

  vestingSchedules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        beneficiary: string;
        totalAmount: bigint;
        released: bigint;
        startTime: bigint;
        duration: bigint;
        cliffDuration: bigint;
        revocable: boolean;
        revoked: boolean;
        earlyUnlockPenalty: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchCreateVestingSchedules"
  ): TypedContractMethod<
    [
      _beneficiaries: AddressLike[],
      _totalAmounts: BigNumberish[],
      _startTime: BigNumberish,
      _duration: BigNumberish,
      _cliffDuration: BigNumberish,
      _revocable: boolean,
      _earlyUnlockPenalty: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beneficiarySchedules"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createVestingSchedule"
  ): TypedContractMethod<
    [
      _beneficiary: AddressLike,
      _totalAmount: BigNumberish,
      _startTime: BigNumberish,
      _duration: BigNumberish,
      _cliffDuration: BigNumberish,
      _revocable: boolean,
      _earlyUnlockPenalty: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "earlyUnlock"
  ): TypedContractMethod<
    [_scheduleId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBeneficiaryInfo"
  ): TypedContractMethod<
    [_beneficiary: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalVested: bigint;
        totalReleasable: bigint;
        beneficiaryTotalReleased: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBeneficiarySchedules"
  ): TypedContractMethod<[_beneficiary: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getReleasableAmount"
  ): TypedContractMethod<[_scheduleId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSchedule"
  ): TypedContractMethod<
    [_scheduleId: BigNumberish],
    [SoulVesting.VestingScheduleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVestedAmount"
  ): TypedContractMethod<[_scheduleId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[_scheduleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[_scheduleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "soulToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalReleased"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVestingAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vestingScheduleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vestingSchedules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        beneficiary: string;
        totalAmount: bigint;
        released: bigint;
        startTime: bigint;
        duration: bigint;
        cliffDuration: bigint;
        revocable: boolean;
        revoked: boolean;
        earlyUnlockPenalty: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "EarlyUnlock"
  ): TypedContractEvent<
    EarlyUnlockEvent.InputTuple,
    EarlyUnlockEvent.OutputTuple,
    EarlyUnlockEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokensReleased"
  ): TypedContractEvent<
    TokensReleasedEvent.InputTuple,
    TokensReleasedEvent.OutputTuple,
    TokensReleasedEvent.OutputObject
  >;
  getEvent(
    key: "VestingRevoked"
  ): TypedContractEvent<
    VestingRevokedEvent.InputTuple,
    VestingRevokedEvent.OutputTuple,
    VestingRevokedEvent.OutputObject
  >;
  getEvent(
    key: "VestingScheduleCreated"
  ): TypedContractEvent<
    VestingScheduleCreatedEvent.InputTuple,
    VestingScheduleCreatedEvent.OutputTuple,
    VestingScheduleCreatedEvent.OutputObject
  >;

  filters: {
    "EarlyUnlock(uint256,address,uint256,uint256)": TypedContractEvent<
      EarlyUnlockEvent.InputTuple,
      EarlyUnlockEvent.OutputTuple,
      EarlyUnlockEvent.OutputObject
    >;
    EarlyUnlock: TypedContractEvent<
      EarlyUnlockEvent.InputTuple,
      EarlyUnlockEvent.OutputTuple,
      EarlyUnlockEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokensReleased(uint256,address,uint256)": TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;
    TokensReleased: TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;

    "VestingRevoked(uint256,address,uint256)": TypedContractEvent<
      VestingRevokedEvent.InputTuple,
      VestingRevokedEvent.OutputTuple,
      VestingRevokedEvent.OutputObject
    >;
    VestingRevoked: TypedContractEvent<
      VestingRevokedEvent.InputTuple,
      VestingRevokedEvent.OutputTuple,
      VestingRevokedEvent.OutputObject
    >;

    "VestingScheduleCreated(uint256,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      VestingScheduleCreatedEvent.InputTuple,
      VestingScheduleCreatedEvent.OutputTuple,
      VestingScheduleCreatedEvent.OutputObject
    >;
    VestingScheduleCreated: TypedContractEvent<
      VestingScheduleCreatedEvent.InputTuple,
      VestingScheduleCreatedEvent.OutputTuple,
      VestingScheduleCreatedEvent.OutputObject
    >;
  };
}
