/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SoulTokenSaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyTokens"
      | "canPurchase"
      | "changePhase"
      | "claimRefund"
      | "contributions"
      | "currentPhase"
      | "enableRefunds"
      | "endSale"
      | "getSaleProgress"
      | "getTokensForAmount"
      | "hardCap"
      | "maxPurchase"
      | "minPurchase"
      | "owner"
      | "paymentToken"
      | "refundClaimed"
      | "refundEnabled"
      | "renounceOwnership"
      | "saleEndTime"
      | "saleStartTime"
      | "setWhitelistEnabled"
      | "softCap"
      | "soulToken"
      | "startSale"
      | "tokenPrice"
      | "tokensPurchased"
      | "totalRaised"
      | "totalTokensSold"
      | "transferOwnership"
      | "updateWhitelist"
      | "whitelist"
      | "whitelistEnabled"
      | "withdrawFunds"
      | "withdrawUnsoldTokens"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsWithdrawn"
      | "OwnershipTransferred"
      | "RefundClaimed"
      | "SaleEnded"
      | "SalePhaseChanged"
      | "TokensPurchased"
      | "WhitelistUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canPurchase",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changePhase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enableRefunds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "endSale", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSaleProgress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokensForAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hardCap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxPurchase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minPurchase",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refundEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "saleEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "saleStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "softCap", values?: undefined): string;
  encodeFunctionData(functionFragment: "soulToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "startSale",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokensPurchased",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRaised",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTokensSold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWhitelist",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUnsoldTokens",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "buyTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changePhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableRefunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endSale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSaleProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokensForAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hardCap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "saleEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "saleStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "softCap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "soulToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startSale", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokensPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRaised",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTokensSold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUnsoldTokens",
    data: BytesLike
  ): Result;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleEndedEvent {
  export type InputTuple = [
    totalRaised: BigNumberish,
    totalTokensSold: BigNumberish
  ];
  export type OutputTuple = [totalRaised: bigint, totalTokensSold: bigint];
  export interface OutputObject {
    totalRaised: bigint;
    totalTokensSold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalePhaseChangedEvent {
  export type InputTuple = [oldPhase: BigNumberish, newPhase: BigNumberish];
  export type OutputTuple = [oldPhase: bigint, newPhase: bigint];
  export interface OutputObject {
    oldPhase: bigint;
    newPhase: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    amount: BigNumberish,
    tokens: BigNumberish
  ];
  export type OutputTuple = [buyer: string, amount: bigint, tokens: bigint];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
    tokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [user: AddressLike, status: boolean];
  export type OutputTuple = [user: string, status: boolean];
  export interface OutputObject {
    user: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SoulTokenSale extends BaseContract {
  connect(runner?: ContractRunner | null): SoulTokenSale;
  waitForDeployment(): Promise<this>;

  interface: SoulTokenSaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyTokens: TypedContractMethod<[_amount: BigNumberish], [void], "payable">;

  canPurchase: TypedContractMethod<[_user: AddressLike], [boolean], "view">;

  changePhase: TypedContractMethod<
    [_newPhase: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<[], [void], "nonpayable">;

  contributions: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  currentPhase: TypedContractMethod<[], [bigint], "view">;

  enableRefunds: TypedContractMethod<[], [void], "nonpayable">;

  endSale: TypedContractMethod<[], [void], "nonpayable">;

  getSaleProgress: TypedContractMethod<[], [bigint], "view">;

  getTokensForAmount: TypedContractMethod<
    [_amount: BigNumberish],
    [bigint],
    "view"
  >;

  hardCap: TypedContractMethod<[], [bigint], "view">;

  maxPurchase: TypedContractMethod<[], [bigint], "view">;

  minPurchase: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  refundClaimed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  refundEnabled: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  saleEndTime: TypedContractMethod<[], [bigint], "view">;

  saleStartTime: TypedContractMethod<[], [bigint], "view">;

  setWhitelistEnabled: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  softCap: TypedContractMethod<[], [bigint], "view">;

  soulToken: TypedContractMethod<[], [string], "view">;

  startSale: TypedContractMethod<
    [_phase: BigNumberish, _duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenPrice: TypedContractMethod<[], [bigint], "view">;

  tokensPurchased: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalRaised: TypedContractMethod<[], [bigint], "view">;

  totalTokensSold: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateWhitelist: TypedContractMethod<
    [_addresses: AddressLike[], _status: boolean],
    [void],
    "nonpayable"
  >;

  whitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  whitelistEnabled: TypedContractMethod<[], [boolean], "view">;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  withdrawUnsoldTokens: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyTokens"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "canPurchase"
  ): TypedContractMethod<[_user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "changePhase"
  ): TypedContractMethod<[_newPhase: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentPhase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "enableRefunds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "endSale"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getSaleProgress"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokensForAmount"
  ): TypedContractMethod<[_amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hardCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxPurchase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minPurchase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundClaimed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "refundEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "saleEndTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "saleStartTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setWhitelistEnabled"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "softCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "soulToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "startSale"
  ): TypedContractMethod<
    [_phase: BigNumberish, _duration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokensPurchased"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRaised"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTokensSold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWhitelist"
  ): TypedContractMethod<
    [_addresses: AddressLike[], _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "whitelistEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawUnsoldTokens"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SaleEnded"
  ): TypedContractEvent<
    SaleEndedEvent.InputTuple,
    SaleEndedEvent.OutputTuple,
    SaleEndedEvent.OutputObject
  >;
  getEvent(
    key: "SalePhaseChanged"
  ): TypedContractEvent<
    SalePhaseChangedEvent.InputTuple,
    SalePhaseChangedEvent.OutputTuple,
    SalePhaseChangedEvent.OutputObject
  >;
  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistUpdated"
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;

  filters: {
    "FundsWithdrawn(address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RefundClaimed(address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "SaleEnded(uint256,uint256)": TypedContractEvent<
      SaleEndedEvent.InputTuple,
      SaleEndedEvent.OutputTuple,
      SaleEndedEvent.OutputObject
    >;
    SaleEnded: TypedContractEvent<
      SaleEndedEvent.InputTuple,
      SaleEndedEvent.OutputTuple,
      SaleEndedEvent.OutputObject
    >;

    "SalePhaseChanged(uint8,uint8)": TypedContractEvent<
      SalePhaseChangedEvent.InputTuple,
      SalePhaseChangedEvent.OutputTuple,
      SalePhaseChangedEvent.OutputObject
    >;
    SalePhaseChanged: TypedContractEvent<
      SalePhaseChangedEvent.InputTuple,
      SalePhaseChangedEvent.OutputTuple,
      SalePhaseChangedEvent.OutputObject
    >;

    "TokensPurchased(address,uint256,uint256)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;

    "WhitelistUpdated(address,bool)": TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
  };
}
