[features]
seeds = false
skip-lint = false

[programs.localnet]
soulcast = "HNjY4deYs1Nuvui7kQwHppmRUw7tiUEPCSEC4q8AH7E6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./deployer-keypair.json"

[programs.devnet]
soulcast = "HNjY4deYs1Nuvui7kQwHppmRUw7tiUEPCSEC4q8AH7E6"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
